#!/usr/bin/env node
/**
 * Generate CSS variables from config.ts
 * Run this script after modifying color values in src/config.ts
 * 
 * Usage: node --loader ts-node/esm scripts/generate-css-vars.ts
 * Or add to package.json: "generate:vars": "tsx scripts/generate-css-vars.ts"
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { themeConfig } from '../src/config.js';

const { light, dark } = themeConfig.colors;

// Helper to convert camelCase to kebab-case
function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

// Generate CSS variable definitions from color object
function generateColorVars(colors: Record<string, string>, indent = '    '): string {
  return Object.entries(colors)
    .map(([key, value]) => `${indent}--color-${toKebabCase(key)}: ${value};`)
    .join('\n');
}

// Build the complete CSS file content
const cssContent = `/* src/styles/global/color.css */
/* 
 * Generated from src/config.ts
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate:vars (or pnpm/yarn equivalent)
 */
@layer base {
  :root {
    /* Brand colors */
${generateColorVars({
  primary: light.primary,
  primaryForeground: light.primaryForeground,
  primaryMuted: light.primaryMuted,
  secondary: light.secondary,
  secondaryForeground: light.secondaryForeground,
  secondaryMuted: light.secondaryMuted,
  accent: light.accent,
  accentForeground: light.accentForeground,
  link: light.link,
})}
    
    /* Content/Surfaces */
${generateColorVars({
  background: light.background,
  backgroundBright: light.backgroundBright,
  foreground: light.foreground,
  card: light.card,
  cardForeground: light.cardForeground,
  muted: light.muted,
  mutedForeground: light.mutedForeground,
  border: light.border,
})}
  }
  
  .dark {
    /* Brand colors */
${generateColorVars({
  primary: dark.primary,
  primaryForeground: dark.primaryForeground,
  primaryMuted: dark.primaryMuted,
  secondary: dark.secondary,
  secondaryForeground: dark.secondaryForeground,
  secondaryMuted: dark.secondaryMuted,
  accent: dark.accent,
  accentForeground: dark.accentForeground,
  link: dark.link,
})}
    
    /* Content/Surfaces */
${generateColorVars({
  background: dark.background,
  backgroundBright: dark.backgroundBright,
  foreground: dark.foreground,
  card: dark.card,
  cardForeground: dark.cardForeground,
  muted: dark.muted,
  mutedForeground: dark.mutedForeground,
  border: dark.border,
})}
  }
}
`;

// Write the generated CSS to the target file
const targetPath = join(process.cwd(), 'src/styles/global/color.css');

try {
  writeFileSync(targetPath, cssContent, 'utf-8');
  console.log('Generated CSS variables successfully!');
  console.log(`Output: ${targetPath}`);
} catch (error) {
  console.error('Error generating CSS variables:', error);
  process.exit(1);
}
