#!/usr/bin/env node
/**
 * Generate CSS variables from src/config.ts
 *
 * - Emits ALL keys found in `themeConfig.colors.light` and `themeConfig.colors.dark`
 * - Converts config keys (camelCase or kebab-case) to kebab-case CSS vars:
 *     key "primaryForeground" -> --color-primary-foreground
 *     key "primary-foreground" -> --color-primary-foreground
 * - Ensures every emitted var has a valid OKLCH triplet (fallback: `0 0 0`)
 *   so UnoCSS theme values like:
 *     oklch(var(--color-primary-foreground) / <alpha-value>)
 *   always remain valid.
 *
 * Recommended package.json script:
 *   "generate:vars": "tsx scripts/generate-css-vars.ts"
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import { themeConfig } from "../src/config.ts";

type ColorMap = Record<string, string | undefined | null>;

const FALLBACK_OKLCH_TRIPLET = "0 0 0";

function toKebabCase(input: string): string {
  // Normalize existing kebab-case and also convert camelCase/PascalCase
  // Examples:
  // - "primaryForeground" => "primary-foreground"
  // - "primary-foreground" => "primary-foreground"
  // - "BackgroundBright" => "background-bright"
  return input
    .replace(/_/g, "-")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/-+/g, "-")
    .toLowerCase()
    .trim();
}

function sanitizeOklchTriplet(value: unknown): string {
  const v = typeof value === "string" ? value.trim() : "";
  return v.length > 0 ? v : FALLBACK_OKLCH_TRIPLET;
}

function unionKeys(...maps: Array<ColorMap | undefined>): string[] {
  const s = new Set<string>();
  for (const m of maps) {
    if (!m) continue;
    for (const k of Object.keys(m)) s.add(k);
  }
  return Array.from(s).sort((a, b) => a.localeCompare(b));
}

function generateVarBlock(colors: ColorMap, keys: string[], indent = "    "): string {
  return keys
    .map((key) => {
      const kebab = toKebabCase(key);
      const value = sanitizeOklchTriplet(colors[key]);
      return `${indent}--color-${kebab}: ${value};`;
    })
    .join("\n");
}

function assertConfigShape(
  cfg: unknown,
): asserts cfg is { colors: { light: ColorMap; dark: ColorMap } } {
  const c: any = (cfg as any)?.colors;
  if (!c || typeof c !== "object") throw new Error("themeConfig.colors is missing");
  if (!c.light || typeof c.light !== "object") throw new Error("themeConfig.colors.light is missing");
  if (!c.dark || typeof c.dark !== "object") throw new Error("themeConfig.colors.dark is missing");
}

function main() {
  assertConfigShape(themeConfig);

  const { light, dark } = themeConfig.colors;

  // Emit the union of keys so light/dark always define the same CSS variables.
  const keys = unionKeys(light, dark);

  const cssContent = `/* src/styles/global/color.css */
/*
 * Generated from src/config.ts
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate:vars (or pnpm/yarn equivalent)
 */
@layer base {
  :root {
${generateVarBlock(light, keys, "    ")}
  }

  .dark {
${generateVarBlock(dark, keys, "    ")}
  }
}
`;

  // Write relative to this script file, not cwd.
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const targetPath = join(__dirname, "..", "src/styles/global/color.css");

  writeFileSync(targetPath, cssContent, "utf-8");
  // eslint-disable-next-line no-console
  console.log("Generated CSS variables successfully!");
  // eslint-disable-next-line no-console
  console.log(`Output: ${targetPath}`);
}

try {
  main();
} catch (err) {
  // eslint-disable-next-line no-console
  console.error("Error generating CSS variables:", err);
  process.exit(1);
}
